### ISSUE TITLE
The user UPN check

### ISSUE THREAD

**Issue by Sam-Hall** [Azure-Samples/azure-mfa-nps-extension-health-check#11]
The check that prompts for a user's UPN assumes the user is in the same domain as the NPS server. I did have the user able to login via RADIUS before installing NPS MFA plugin. After installation, NPS just fails to respond with "The request was discarded by a third-party extension DLL file." in the logs.

The "all users" test just hangs on "Checking Accessibility to https://login.microsoftonline.com". Does this thing use system proxy settings, because the site is perfectly available via the browser.

**Comment by Justinha** [comment]
@Sam-Hall sorry for delay. I think recent merges have fixed this issue.
