### ISSUE TITLE
Incorrect Reporting of Azure MFA SPN - Check

### ISSUE THREAD

**Issue by shann1976** [Azure-Samples/azure-mfa-nps-extension-health-check#12]
Hi,

I found out this excellent script, however found an issue with the script. The script reports that :

Checking if Azure MFA SPN is Exist in the tenant >> Test Failed >> Check if you have a valid MFA License for Azure MFA NPS: https://docs.microsoft.com/en-us/azure/active-directory/authentication/howto-mfa-nps-extension#licenses >> If there is a valid Non expired license, then consult MS Support

I have Azure AD P1 trial license enabled and have checked that both the below are enabled (Enabled for users to sign-in? yes) in my tenant:
Azure Multi-Factor Auth Connector / App ID = 1f5530b3-261a-47a9-b357-ded261e17918
and
Azure Multi-Factor Auth Client / App ID = 981f26a1-7f43-403b-a875-f8b09b8cd720

The command line outputs of:

> Get-MsolServicePrincipal -AppPrincipalId "981f26a1-7f43-403b-a875-f8b09b8cd720" | fl *
> 
> ExtensionData         : System.Runtime.Serialization.ExtensionDataObject
> AccountEnabled        : True
> Addresses             : {Microsoft.Online.Administration.RedirectUri, Microsoft.Online.Administration.RedirectUri}
> AppPrincipalId        : 981f26a1-7f43-403b-a875-f8b09b8cd720
> DisplayName           : Azure Multi-Factor Auth Client
> ObjectId              : dbeae339-562c-4884-92a5-e821927bb31f
> ServicePrincipalNames : {981f26a1-7f43-403b-a875-f8b09b8cd720}
> TrustedForDelegation  : False

> Get-MsolServicePrincipal -AppPrincipalId "1f5530b3-261a-47a9-b357-ded261e17918" | fl *
> 
> ExtensionData         : System.Runtime.Serialization.ExtensionDataObject
> AccountEnabled        : True
> Addresses             : {}
> AppPrincipalId        : 1f5530b3-261a-47a9-b357-ded261e17918
> DisplayName           : Azure Multi-Factor Auth Connector
> ObjectId              : 2f1ba8b5-cb27-4683-afd0-143dfa88afab
> ServicePrincipalNames : {1f5530b3-261a-47a9-b357-ded261e17918, https://adnotifications.windowsazure.com/StrongAuthenticationService.svc/Connector,
>                         https://adnotifications.windowsazure.us/StrongAuthenticationService.svc/Connector}
> TrustedForDelegation  : False

Is this because of trials OR something else?

**Comment by Justinha** [comment]
@shann1976 Sorry for delay. I think recent merges have fixed this.
