### ISSUE TITLE
Checking if Azure MFA SPN is Exist in the tenant - Test Failed

### ISSUE THREAD

**Issue by weyCC81** [Azure-Samples/azure-mfa-nps-extension-health-check#17]
What is happening:

> $AllSPNs = Get-MsolServicePrincipal | select AppPrincipalId
> WARNING: More results are available. Please specify one of the All or MaxResults parameters.

What should be changed:

`#$AllSPNs = Get-MsolServicePrincipal | select AppPrincipalId`
`$AllSPNs = Get-MsolServicePrincipal -All | select AppPrincipalId`

**Comment by Justinha** [comment]
@weyCC81 sorry for delay and thank you for the correction. This is fixed.
