### ISSUE TITLE
Add Contributors, which Checks Issues & Pull requests

### ISSUE THREAD

**Issue by weyCC81** [Azure-Samples/azure-mfa-nps-extension-health-check#18]
Contributors
iainfoulds Iain Foulds --> Works at Google

People Reference:
https://docs.microsoft.com/en-us/azure/active-directory/authentication/howto-mfa-nps-extension-errors

People Tag:
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

@MicrosoftGuyJFlo 
@DCtheGeek

**Comment by weyCC81** [comment]
@jennyf19
@jmprieur
@Shama-K

@derisen

@jeffpatt24
@surendernitj
@YunZhou-MS
@RenaShahMSFT
@mtalasila

**Comment by jennyf19** [comment]
@weyCC81 can you provide some context on to what this issue is for? thank you.

**Comment by weyCC81** [comment]
@jennyf19 It looks like nobody is maintaining this repository, as the current contributor works for Google since some time.

**Comment by weyCC81** [comment]
@jennyf19 any response on this?

Contributors:
    @microsoftopensource --> Placeholder
    @iainfoulds --> Offline
    @microsoft-github-operations --> Bot

**Comment by BuckeyeGuyJFlo** [comment]
This was created after I was no longer responsible for MFA content. @JustinHa currently owns MFA content and may be able to find someone in support who can maintain the script if there is something wrong.

**Comment by weyCC81** [comment]
@Justinha please update contributor on this project. verify check pull requests & issues


█▀▀ █▀█ █▀▄ █▀▀   █▀█ █▀▀ █░█ █ █▀▀ █░█░█
█▄▄ █▄█ █▄▀ ██▄   █▀▄ ██▄ ▀▄▀ █ ██▄ ▀▄▀▄▀

**Comment by weyCC81** [comment]
Please resolve this
@Justinha
@MicrosoftGuyJFlo 
@JamesTran-MSFT 
@jennyf19
@TimShererWithAquent
@mprentice22153

**Comment by weyCC81** [comment]
Please resolve this
@Justinha
@MicrosoftGuyJFlo
@JamesTran-MSFT
@jennyf19
@TimShererWithAquent
@mprentice22153

**Comment by weyCC81** [comment]
Please resolve this:
@TravisCragg-MSFT
@ktoliver
@stegag
@ShannonLeavitt
@Court72
@tomaschladek

**Comment by tfosmark** [comment]
@weyCC81 I'll send email to the C+L governance team about this repo ownership issue. I'm sure they can sort it out.

cc: @snoviking

**Comment by weyCC81** [comment]
Any response form C+L governance team available?

@tfosmark 
@snoviking

**Comment by weyCC81** [comment]
@Justinha This can be closed if there is some frequent work planned on this repo.
