### ISSUE TITLE
Script readme.md is for a different script entirely

### ISSUE THREAD

**Issue by ctxcommunity** [Azure-Samples/azure-mfa-nps-extension-health-check#19]
The script azuremfahealthcheck.ps1 does not exist in this repository nor does the provided NPS_MFA_Troubleshooter.ps1 provide the same .html output that I'm looking for.   I simply want to check to see if the NPS server with Azure Extensions has been configured properly by the customer.  The azuremfahealthcheck.ps1 appears to accomplish this (based on the screenshot) where as the NPS_MFA_Troubleshooter.ps1 does not (based on actually using it)

**Comment by alejandrorivadeneira** [comment]
I agree with this comment. Did anyone manage to find the original script that actually does what is described in the Readme section?

**Comment by technion** [comment]
If you look here for example:

https://github.com/Azure-Samples/azure-mfa-nps-extension-health-check/blob/master/MFA_NPS_Troubleshooter.ps1#L531

You'll see that some of the code in the screenshot does actually exist - it's just has huge commented sections, as though it's some sort of WIP. I've looked into the possibility of fixing this myself but giving #18 it doesn't look like there's a chance of a merge.

**Comment by Justinha** [comment]
@ctxcommunity @technion sorry I don't know the script history and can't reproduce the original.
