### ISSUE TITLE
"Checking if the SPN for Azure MFA is Exist and Enabled" Test Fails

### ISSUE THREAD

**Issue by andyKalman** [Azure-Samples/azure-mfa-nps-extension-health-check#2]
This test fails if the max results are exceeded for the number of SPNs in your tenant. A false positive is created as a result. Simply adding the `-All` parameter to `Get-MsolServicePrincipal` alleviates this. I'll create a PR for this shortly. 
![healthcheck](https://user-images.githubusercontent.com/8703771/76886404-02a74880-683e-11ea-9fe0-03161a9a9f1c.png)

**Comment by jaegerschnitzel** [comment]
I also had the same issue. Why was the PR not accepted yet?

**Comment by jaegerschnitzel** [comment]
I also had the same issue. Why was the PR not accepted yet?
