### ISSUE TITLE
MFA_NPS_Troubleshooter.ps1 script not working as expected

### ISSUE THREAD

**Issue by ArslanAyoob** [Azure-Samples/azure-mfa-nps-extension-health-check#20]
I run the following script, and it didnt the health check.

Is this the right script , also i am try to connect to the azure tennant as a owner, it is not working.

Has, there been any changes on the script, or that's the original one.

**Comment by technion** [comment]
See https://github.com/Azure-Samples/azure-mfa-nps-extension-health-check/issues/19 and https://github.com/Azure-Samples/azure-mfa-nps-extension-health-check/issues/18 .

You're using a script on an abandoned repo that contains a completely different script to what is advertised.

**Comment by Justinha** [comment]
@ArslanAyoob sorry for delay. many fixes have been merged. please retry.
