### ISSUE TITLE
Add Checks for Version 1.1.01850.1

### ISSUE THREAD

**Issue by weyCC81** [Azure-Samples/azure-mfa-nps-extension-health-check#22]
Release Notes:
> * Changed the Azure endpoint to increase resiliency.
>   The NPS server must be able to communicate with the following URLs over port 443:
>     strongauthenticationservice.auth.microsoft.com (new)
>     adnotifications.windowsazure.com
> * Fixed an issue where event logs showed a username with incorrect encoding.
>   Radius values are now read as UTF-8 instead of attempting to detect encoding.
>   The registry entry USERNAME_ENCODING can be set to "Detect" to use the previous encoding detection behavior.
> * Improved cache management.
>   This reduces occurence of high CPU utilization in busy or long running systems.
> * Improved LDAP search performance for systems that have several forests specified in the registry entry LDAP_LOOKUP_FORESTS.
> * Support for Windows Server 2022.
> * Upgraded to Visual C++ redistributable for Visual Studio 2017.

Add Check for the following URL:

- strongauthenticationservice.auth.microsoft.com (new)

**Comment by Lawike2** [comment]
I have been unable to download this latest version. The previous version is failing for NPS health check version status. I downloaded the latest version, but it is still showing the previous version 1.1.1850.1. Please I need assistance.

**Comment by Justinha** [comment]
@weyCC81 thank you! @Lawike2 please retry should be fixed now.
