### ISSUE TITLE
Stop-Service Requires a -Force to Successfully Stop The Service

### ISSUE THREAD

**Issue by SweetAsNZ** [Azure-Samples/azure-mfa-nps-extension-health-check#23]
Stop-Service Requires a -Force to Successfully Stop The Service

**Comment by SweetAsNZ** [comment]
Pull request: #25

**Comment by sideone** [comment]
had the same issue. to stop the service, had to bits of code from this function.

https://mikefrobbins.com/2013/08/29/powershell-function-to-stop-a-windows-service-with-a-status-of-stopping/

**Comment by Justinha** [comment]
@SweetAsNZ thank you! PR is merged. #please-close
