### ISSUE TITLE
Re-register the MFA extension check

### ISSUE THREAD

**Issue by sideone** [Azure-Samples/azure-mfa-nps-extension-health-check#26]
Great script! saved me hours troubleshooting an expired cert issue today.

![image](https://user-images.githubusercontent.com/723468/159530306-cc2c7de7-2081-48ee-8827-4a5d4f17a815.png)

![image](https://user-images.githubusercontent.com/723468/159530151-e3bdd00a-5b30-421d-885f-9c9e0928b42d.png)

`$AZURE_MFA_HOSTNAME = (Get-ItemProperty -path HKLM:\SOFTWARE\Microsoft\AzureMfa -name "AZURE_MFA_HOSTNAME").AZURE_MFA_HOSTNAME`

:380 , i think this line should be updated to match the AZURE_MFA_RESOURCE_HOSTNAME to complete the check

Also, small spelling typo
regstries should be changed to registries

**Comment by Justinha** [comment]
@sideone thank you! The spelling is fixed. Can you kindly submit a pull request with the change you wish to make?
