### ISSUE TITLE
Registry backup is not verified before deleting values

### ISSUE THREAD

**Issue by jlfrank83** [Azure-Samples/azure-mfa-nps-extension-health-check#27]
In the MFAorNPS Function:

reg export hklm\system\currentcontrolset\services\authsrv c:\nps\AuthSrv.reg /y 

Set-ItemProperty -Path Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\AuthSrv\Parameters -Name AuthorizationDLLs -Value ''
Set-ItemProperty -Path Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\AuthSrv\Parameters -Name ExtensionDLLs -Value ''

There is no verification that the export was successful before the values are deleted, and therefore the s

**Comment by Justinha** [comment]
@jlfrank83 Thanks for commenting but I don't fully understand what needs to be done. Can you submit a PR?
