### ISSUE TITLE
Troubleshooting script problem

### ISSUE THREAD

**Issue by sip03ds** [Azure-Samples/azure-mfa-nps-extension-health-check#29]
Just cloned the repo to get the file. 
Tried to run the file on an NPS 2019 with Azure MFA extension and I get the following errors: 

At C:\Users\<my user>\Desktop\MFA_NPS_Troubleshooter.ps1:216 char:293
+ ...  + $MFAVersion + ". The latest version is: " + $latestMFAVersion "."}
+                                                                      ~~~
Unexpected token '"."' in expression or statement.
At C:\Users\<my user>\Desktop\MFA_NPS_Troubleshooter.ps1:216 char:292
+ ...  + $MFAVersion + ". The latest version is: " + $latestMFAVersion "."}
+                                                                     ~
The hash literal was incomplete.
At C:\Users\t1_distathopoulos\Desktop\MFA_NPS_Troubleshooter.ps1:638 char:1
+ }
+ ~
Unexpected token '}' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : UnexpectedToken

**SOLUTION:**
- line 216 there is a "+" missing at the end to connect the variable with the string "."

**Comment by nathanmcnulty** [comment]
This was my fault, and I just submitted a PR to address it.  I must have messed something up between VS Code and testing on the NPS server...

I generally don't use + to concatenate strings but was trying to leave things similar to the original code. I went ahead and updated it to no longer use +'s.

**Comment by Justinha** [comment]
@sip03ds @nathanmcnulty fixed now. Thanks!

**Comment by Justinha** [comment]
#please-close
