### ISSUE TITLE
Connection to Azure Failed running script

### ISSUE THREAD

**Issue by mahuen** [Azure-Samples/azure-mfa-nps-extension-health-check#34]
Hi, when I run the script it shows this connection message (option 2 was selected):

**Connection to Azure Failed - Skipped all test, please make sure to connect to your tenant first with global admin role...**

My question is: ¿in which step of the script I should provide the global admin credencial?

**Comment by jbenson444** [comment]
@mahuen Probably too late for you, but in case someone else sees this, the solution is to run the following in PowerShell, restart the session, and you should be good to go:  [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

**Comment by Justinha** [comment]
#please-close
