### ISSUE TITLE
Checking Other MFA Registry Status

### ISSUE THREAD

**Issue by kyjones03** [Azure-Samples/azure-mfa-nps-extension-health-check#36]
Hello,

I noticed that the script checks registry values below and marks the test as failed if the values do not match. However, it looks like this needs to be updated to reflect the most recent registry values. See attached image of default reg values after installing the Azure MFA NPS extension. 

Please confirm if this is the case. Thank you.

Write-Host "7- Checking other Azure MFA related Registry keys have the right values ... " -ForegroundColor Yellow
Write-Host

$AZURE_MFA_HOSTNAME = (Get-ItemProperty -path HKLM:\SOFTWARE\Microsoft\AzureMfa -name "AZURE_MFA_HOSTNAME").AZURE_MFA_HOSTNAME

$AZURE_MFA_TARGET_PATH = (Get-ItemProperty -path HKLM:\SOFTWARE\Microsoft\AzureMfa -name "AZURE_MFA_TARGET_PATH").AZURE_MFA_TARGET_PATH

$CLIENT_ID = (Get-ItemProperty -path HKLM:\SOFTWARE\Microsoft\AzureMfa -name "CLIENT_ID").CLIENT_ID

$STS_URL = (Get-ItemProperty -path HKLM:\SOFTWARE\Microsoft\AzureMfa -name "STS_URL").STS_URL

if ($AZURE_MFA_HOSTNAME -eq "adnotifications.windowsazure.com" -and $AZURE_MFA_TARGET_PATH -eq "StrongAuthenticationService.svc/Connector" -and $CLIENT_ID -eq "981f26a1-7f43-403b-a875-f8b09b8cd720" -and $STS_URL -eq "https://login.microsoftonline.com/")
![AzureMFARegKeys](https://user-images.githubusercontent.com/75283373/172733677-6a8cd1a1-0a74-4b3b-ab92-7c78222615aa.png)

**Comment by kyjones03** [comment]
@Justinha Hello, is it possible for you to review this issue and confirm? Thank you.

**Comment by MoccaMan** [comment]
@MubDubs  I can confirm this.
If you change Registry AZURE_MFA_HOSTNAME to adnotifications.windowsazure.com the test passes. However this is most likely not the correct value, as the installscript sets it to the value as seen in your screendump

Perhaps an update to the script is coming.

**Comment by ahshek999** [comment]
@MoccaMan Agree not more with your explanation

Let's wait for the update script

**Comment by Justinha** [comment]
@kyjones03 @MoccaMan @ahshek999 sorry for delay and thanks for raising this. I created an internal work item for SMEs to review and update script as needed. #please-close

**Comment by kyjones03** [comment]
@Justinha thank you for your update!

**Comment by ahshek999** [comment]
Thx for the update
