### ISSUE TITLE
Checking for Special Character (e.g. Carriage Return) in UPN

### ISSUE THREAD

**Issue by weyCC81** [Azure-Samples/azure-mfa-nps-extension-health-check#37]
Eventlog Error:

> NPS Extension for Azure MFA:  CID: [GUID] : Request Discard for user [UPN]
>  with Azure MFA response: UserNotFound and message: The specified user was not found.,,,[GUID]

Troubleshooting Error:
> "For some reason, we are not able to get the SAMACCOUNTNAME for" $Global:UPN "From Local AD ... Hence we consider test was failed ..."

Please add an additional check if the UPN includers an Carriage Return or other unsupported Metacharacter:
```
Get-ADUser -Properties * -Filter * | Select UserPrincipalName | Where {$_ -match '\r'}
Get-ADUser -Properties * -Filter * | Select UserPrincipalName | Where {$_ -match '\s'}
```

`if($Global:UPN -match '\r') {
Write-Host
Write-Host "User" $Global:UPN "includes a Metacharacter in local AD  ... You Need to remove the Carriage Return, Space, New line from the UserPrincipalName" -ForegroundColor Red
Write-Host "Refer to [URL] for more infor about this option " -ForegroundColor Red
Write-Host
}
`

**Comment by Justinha** [comment]
@weyCC81 sorry for delay and thanks for raising this. I created an internal work item for SMEs to review and update script as needed. #please-close
