### ISSUE TITLE
accountskuid requires update

### ISSUE THREAD

**Issue by BronsonMagnan** [Azure-Samples/azure-mfa-nps-extension-health-check#4]
accountskuid for indirect CSPs wil show up like this, with reseller-account: prefixed, causing the licensing test to fail.

```
reseller-account:WIN10_VDA_E5
reseller-account:EMS
reseller-account:ATP_ENTERPRISE
reseller-account:ENTERPRISEPACK
```

**Comment by weyCC81** [comment]
Message
> "User " $Global:UPN "has not a valid license for MFA, it's a warning message to be legal from licensing side... Test FAILED" 
>"Test will continue to detect additional issue(s), Please make sure to assign a valid MFA License for the user (AD Premium, EMS or MFA standalone license"

Chang to (Get-MsolUser -UserPrincipalName $upn).Licenses[2].ServiceStatus needed for the Request
```
reseller-account:DYN365_SALES_PRO
reseller-account:ATP_ENTERPRISE
reseller-account:SPE_E3
```

or "(Get-AzureADUser -ObjectId $upn).AssignedPlans"
