### ISSUE TITLE
Missing closing '}' in statement block or type definition.

### ISSUE THREAD

**Issue by daniel-kuhn-ict** [Azure-Samples/azure-mfa-nps-extension-health-check#40]
Receiving this error

At MFA_NPS_Troubleshooter.ps1:88 char:1
+ {
+ ~
Missing closing '}' in statement block or type definition.
At C:\Program Files\Microsoft\AzureMfa\MFA_NPS_Troubleshooter.ps1:49 char:34
+ Function Check_Nps_Server_Module {
+                                  ~
Missing closing '}' in statement block or type definition.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : MissingEndCurlyBrace

**Comment by Justinha** [comment]
@daniel-kuhn-ict sorry for delay and thanks for raising this. I created an internal work item for SMEs to review and update script as needed. #please-close
