### ISSUE TITLE
Update README.md with what the script actually does

### ISSUE THREAD

**Issue by simbrar49** [Azure-Samples/azure-mfa-nps-extension-health-check#43]
The script that's described in [README.md](https://github.com/Azure-Samples/azure-mfa-nps-extension-health-check/blob/main/README.md) is different from the script that's currently available: [MFA_NPS_Troubleshooter.ps1](https://github.com/Azure-Samples/azure-mfa-nps-extension-health-check/blob/main/MFA_NPS_Troubleshooter.ps1). While I understand this has been brought up before (https://github.com/Azure-Samples/azure-mfa-nps-extension-health-check/issues/19, https://github.com/Azure-Samples/azure-mfa-nps-extension-health-check/issues/20) it would be helpful if README.md was updated to reflect what the current script actually does; for instance:

- Which tests are available?
- What does each test do? (i.e. what does each test create, read, update, and/or delete (CRUD)?)
- What's the impact of running each test? (e.g. does the NPS extension need to be stopped and/or restarted?)
- What permissions are required to complete each test? (e.g. local administrator on the server, Global Administrator on Azure AD?)

This information would make it easier to make an informed decision with respect to the type of test(s) to run as well as determining the impact(s) of running the test(s); something that's absolutely critical for production NPS environments.

**Comment by Justinha** [comment]
@simbrar49 Thanks for raising this. Huge thanks to @miguel-s-ferreira for revising the Readme!

**Comment by Justinha** [comment]
The update is merged.
