### ISSUE TITLE
Expiration Check of Certificate

### ISSUE THREAD

**Issue by sethallums** [Azure-Samples/azure-mfa-nps-extension-health-check#46]
Running the script, the HTML report showed everything as having passed, yet our implementation was not working. We discovered later on that it was due to the self-signed certificate having expired. The tool did not report this (it showed the certificate as having passed). It would be nice to have the tool check the expiration of the certificate and notify if it was expired or not.

**Comment by Justinha** [comment]
@sethallums thanks for the feedback and thanks to @miguel-s-ferreira for submitting the fix https://github.com/Azure-Samples/azure-mfa-nps-extension-health-check/pull/49 

Certificate validity is evaluated by script, if certificate exists on Azure AD and on NPS Server at same time ONLY. If it's removed by any mean from one of these 2 locations, script will consider that there is no relationship between NPS Extension OnPrem and NPS Extension on Azure AD
