### ISSUE TITLE
"Checking if there is a matched certificate with Azure MFA" will fail if there is only 1 matched certificate

### ISSUE THREAD

**Issue by jessie-pang** [Azure-Samples/azure-mfa-nps-extension-health-check#5]
The "Checking if there is a matched certificate with Azure MFA" will fail (and appear twice in the report) if there is only 1 matched certificate:
![image](https://user-images.githubusercontent.com/35220454/85644901-d2880500-b6ca-11ea-99b6-b32a88502cb3.png)

When the $MatchedCert only has 1 item, it will be considered as a string. And the $MatchedCert[0] will be the first character, instead of the whole string (certificate thumbprint):
![image](https://user-images.githubusercontent.com/35220454/85645244-b9cc1f00-b6cb-11ea-9a48-5ab49eca2e13.png)

The issue can be resolved by modifying the line from:

**$MatchedCert = $TP | Where {$localCert -Contains $_}**

To:

**$MatchedCert = @($TP | Where {$localCert -Contains $_})**

![image](https://user-images.githubusercontent.com/35220454/85645487-77571200-b6cc-11ea-8073-7f1a4db53801.png)

**Comment by Justinha** [comment]
@jessie-pang thank you! this is fixed.
