### ISSUE TITLE
test one user gives wrong MFA licens info

### ISSUE THREAD

**Issue by Keldandorin** [Azure-Samples/azure-mfa-nps-extension-health-check#51]
When testaing a user with a Microsoft 365 Business Premium it says
User  test-user@testdomain.com has not a valid license for MFA, it's a warning message to be legal from licensing side... Test FAILED.

I think that is the wrong outcome sins Microsoft 365 Business Premium is ok for MFA

**Comment by Justinha** [comment]
@Keldandorin thanks for reporting this and thanks to @miguel-s-ferreira for fixing it
