### ISSUE TITLE
"Option 0: Isolate the Cause of the issue: if it's NPS or MFA issue" - NPS service needs to be restarted after modifying the registries

### ISSUE THREAD

**Issue by jessie-pang** [Azure-Samples/azure-mfa-nps-extension-health-check#6]
For "Option 0: Isolate the Cause of the issue: if it's NPS or MFA issue", the NPS service needs to be restarted after modifying the registries, in order for the changes to take effect.

Restart-Service -Force ias

**Comment by Justinha** [comment]
@jessie-pang Thanks for your comment and sorry for delay. I'm not sure if this is still an issue because I don't see Option 0 after latest merges. If it is still a problem, please submit a pull request with the change you want to see.
