### ISSUE TITLE
Please add supportability to AzureChinaCloud 

### ISSUE THREAD

**Issue by jessie-pang** [Azure-Samples/azure-mfa-nps-extension-health-check#7]
Currently the script is specific for public Azure cloud. Since the feature is supported in Azure China cloud, please add the supportability to Azure China as well. Basically, only the URLs need to be modified:

login.microsoftonline.com ---> login.chinacloudapi.cn
adnotifications.windowsazure.com ---> adnotifications.windowsazure.cn

Thank you.

**Comment by Justinha** [comment]
@jessie-pang Sorry for delay and thanks for the suggestion. Can you submit a pull request for this? I'm unsure how to add it.
